# Python Numpy Intro¶
###### An introduction to the Python Numpy numerical python library. It is 3x to 10x faster and more memory efficient than Python's lists because, similar to Java arrays, it uses contiguous blocks of memory, and all elements are the same data type so there is no type checking at runtime. The Numpy library also includes many built-in code-saving mathematical functions that can be performed on an entire array or any slice of an array with a single line of code (ie. no for loops).Numpy n-dimensional arrays are also sometimes referred to as nd-arrays.

In [1]:
import numpy as np

Creating a Numpy Array

In [2]:
a = np.array([1,3,5,7,9,11])
print(a)

[ 1  3  5  7  9 11]


In [4]:
a = np.arange(1, 20, 1.5)    # (start, stop, step)
print(a)

[ 1.   2.5  4.   5.5  7.   8.5 10.  11.5 13.  14.5 16.  17.5 19. ]


In [5]:
a = np.linspace(5, 9, 20)  # (start, stop, number of items)
print(a)

[5.         5.21052632 5.42105263 5.63157895 5.84210526 6.05263158
 6.26315789 6.47368421 6.68421053 6.89473684 7.10526316 7.31578947
 7.52631579 7.73684211 7.94736842 8.15789474 8.36842105 8.57894737
 8.78947368 9.        ]


In [6]:
a = np.zeros((4, 2)) # Array of Zeroes
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
a = np.ones((2, 3), dtype=np.int16) # Array of ones
print(a)

[[1 1 1]
 [1 1 1]]


In [8]:
a = np.full((6,), 88)  # Array of 88
print(a)

[88 88 88 88 88 88]


In [10]:
a = np.fromstring('25 30 35 40', dtype=np.int64, sep=' ') #array with integer converted from string
print(a)

[25 30 35 40]


In [11]:
a = np.array([[1,3,5],[7,9,11]]) #2D array
print(a)

[[ 1  3  5]
 [ 7  9 11]]


In [12]:
b = np.zeros_like(a)    # _like gives you a new array in the same shape as the argument.
print(b)

[[0 0 0]
 [0 0 0]]


In [15]:
a = np.linspace(5, 9, 20)  # (start, stop, number of items)
print(a.size) #size (number of items)

20


In [16]:
print(a.shape) #shape (dimensions)

(20,)


In [18]:
print(a.ndim) #No of dimensions

1


In [19]:
a = np.array([[1,3,5],[7,9,11]]) #2D array
print(a)

[[ 1  3  5]
 [ 7  9 11]]


In [21]:
print(a.shape)
print(a.ndim)

(2, 3)
2


In [22]:
print(a.itemsize) #itemsize(bytes of memory for each item)

4


In [23]:
print(a.dtype) #dtype (numpy data type)

int32


In [24]:
print(a.nbytes)  # same as a.size * a.itemsize

24


Indexing and Slicing

In [25]:
print(a)

[[ 1  3  5]
 [ 7  9 11]]


In [27]:
print(a[1]) #Indexing

[ 7  9 11]


In [28]:
print(a[0][2]) #Indexing in 2d array

5


In [33]:
print(a[:1]) # Slicing

[[1 3 5]]


In [34]:
print(a[1:3:2])

[[ 7  9 11]]


In [35]:
print(a[:, 1:2])  # all elements on dimension 0, only element 1 on dimension 1

[[3]
 [9]]


In [39]:
a = np.arange(-10, -4,).reshape(2,3)
print(a)

[[-10  -9  -8]
 [ -7  -6  -5]]


In [40]:
a = a.swapaxes(0,1)
print(a)

[[-10  -7]
 [ -9  -6]
 [ -8  -5]]


In [41]:
a = a.flatten()
print(a)

[-10  -7  -9  -6  -8  -5]


In [59]:
d = np.arange(0,100)
print(d.dtype, type(d[1]))
print(d.nbytes)

int32 <class 'numpy.int32'>
400


In [60]:
d = np.arange(0,100, dtype='int8')
print(d.dtype, type(d[1]))
print(d.nbytes)

int8 <class 'numpy.int8'>
100


In [44]:
e = np.array([(1.566666,2,3), (4,5,6)])
print(e.dtype)

float64


In [45]:
e = e.round(4)
print(e)


[[1.5667 2.     3.    ]
 [4.     5.     6.    ]]


In [46]:
np.set_printoptions(precision=2, suppress=True)    # show 2 decimal places, suppress scientific notation
print(e)

[[1.57 2.   3.  ]
 [4.   5.   6.  ]]


In [47]:
import pprint as pp
pp.pprint(np.sctypes)  # Data types in Numpy

{'complex': [<class 'numpy.complex64'>, <class 'numpy.complex128'>],
 'float': [<class 'numpy.float16'>,
           <class 'numpy.float32'>,
           <class 'numpy.float64'>],
 'int': [<class 'numpy.int8'>,
         <class 'numpy.int16'>,
         <class 'numpy.int32'>,
         <class 'numpy.int64'>],
 'others': [<class 'bool'>,
            <class 'object'>,
            <class 'bytes'>,
            <class 'str'>,
            <class 'numpy.void'>],
 'uint': [<class 'numpy.uint8'>,
          <class 'numpy.uint16'>,
          <class 'numpy.uint32'>,
          <class 'numpy.uint64'>]}


In [61]:
print(d)
print(d > 4)
print(d ** 2 - 1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[False False False False False  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]
[  -1    0    3    8   15   24   35   48   63   80   99  120 -113  -88
  -61  -32   

In [62]:
print(d.min())

0


In [63]:
print(d.max())

99


In [64]:
print(d.sum())

4950


In [65]:
print(d.mean())

49.5


In [66]:
print(d.var())

833.25


In [67]:
print(d.std())

28.86607004772212


In [69]:
print(d.argmin())  # index of min element

0


In [70]:
print(d.argmax())      # index of max element

99


In [71]:
print(d.argsort())     # returns array of indices that would put the array in sorted order

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [80]:
g=np.array([[80,8,63,48,35,0,1,15,3,24],
 [0,48,15,80,3,35,63,8,24,1],
 [15,63,18,80,24,48,3,35,1,0],
 [0,48,15,3,24,80,35,63,1,8],
 [1,48,24,3,63,35,8,15,0,80],
 [24,80,0,15,48,1,8,35,63,3]])
print(g)

[[80  8 63 48 35  0  1 15  3 24]
 [ 0 48 15 80  3 35 63  8 24  1]
 [15 63 18 80 24 48  3 35  1  0]
 [ 0 48 15  3 24 80 35 63  1  8]
 [ 1 48 24  3 63 35  8 15  0 80]
 [24 80  0 15 48  1  8 35 63  3]]


In [81]:
print(g > 4)
print(g ** 2 - 1)

[[ True  True  True  True  True False False  True False  True]
 [False  True  True  True False  True  True  True  True False]
 [ True  True  True  True  True  True False  True False False]
 [False  True  True False  True  True  True  True False  True]
 [False  True  True False  True  True  True  True False  True]
 [ True  True False  True  True False  True  True  True False]]
[[6399   63 3968 2303 1224   -1    0  224    8  575]
 [  -1 2303  224 6399    8 1224 3968   63  575    0]
 [ 224 3968  323 6399  575 2303    8 1224    0   -1]
 [  -1 2303  224    8  575 6399 1224 3968    0   63]
 [   0 2303  575    8 3968 1224   63  224   -1 6399]
 [ 575 6399   -1  224 2303    0   63 1224 3968    8]]


In [82]:
print(g.min())

0


In [83]:
print(g.max())

80


In [84]:
print(g.sum())

1672


In [85]:
print(g.mean())

27.866666666666667


In [86]:
print(g.var())    

705.0822222222222


In [87]:
print(g.std())      

26.553384383581356


In [88]:
print(g.sum(axis=1))

[277 277 287 277 277 277]


In [89]:
print(g.min(axis=0))

[0 8 0 3 3 0 1 8 0 0]


In [90]:
print(g.argmin())

5


In [91]:
print(g.argmax())

0


In [92]:
print(g.argsort())

[[5 6 8 1 7 9 4 3 2 0]
 [0 9 4 7 2 8 5 1 6 3]
 [9 8 6 0 2 4 7 5 1 3]
 [0 8 3 9 2 4 6 1 7 5]
 [8 0 3 6 7 2 5 1 4 9]
 [2 5 9 6 3 0 7 4 8 1]]


In [94]:
print(g[:, 2:3])

[[63]
 [15]
 [18]
 [15]
 [24]
 [ 0]]


In [95]:
print(g[:, 2:3].max())

63


In [96]:
col3 = g[:, 3:4]      # not a copy, just a pointer to a slice of g
print(col3.std())

33.183412857765084


In [97]:
col3 *= 100           # Beware: this is applied to g data
print(g)

[[  80    8   63 4800   35    0    1   15    3   24]
 [   0   48   15 8000    3   35   63    8   24    1]
 [  15   63   18 8000   24   48    3   35    1    0]
 [   0   48   15  300   24   80   35   63    1    8]
 [   1   48   24  300   63   35    8   15    0   80]
 [  24   80    0 1500   48    1    8   35   63    3]]


In [98]:
np.set_printoptions(precision=5, suppress=True)    # show 5 decimal places, suppress scientific notation
h = np.random.random(6)
print(h)


[0.78464 0.21424 0.17614 0.22243 0.01864 0.88523]


In [99]:
h = np.random.randint(10, 99, 8)    # (low, high inclusive, size)
print(h)

[85 39 43 92 41 13 87 44]


In [100]:
np.random.shuffle(h)        # in-place shuffle
print(h)

[87 13 44 41 43 85 92 39]


In [101]:
print(np.random.choice(h))

92


In [102]:
h.sort()                    # in-place sort
print(h)

[13 39 41 43 44 85 87 92]
